import { useEffect, useMemo, useState, type CSSProperties, type Dispatch, type FormEvent, type SetStateAction } from 'react';
import { Link, Route, Switch, useLocation, useParams } from 'wouter';
import { Bookmark, BookOpen, Check, ChevronLeft, ChevronRight, Heart, LibraryBig, List, Moon, Search, Settings as SettingsIcon, Sun, Upload, X } from 'lucide-react';

type Book = { id: string; title: string; author: string; genre: string; color: string; pages: string[]; description: string; };
type Prefs = { displayName: string; theme: 'light' | 'dark' | 'paper'; font: 'Literata' | 'Georgia' | 'DM Sans'; size: number; spacing: number; };
type LocalPdf = { id: string; title: string; url: string; };
const books: Book[] = [
  { id:'tideline', title:'The Quiet Between Tides', author:'Mara Ellery', genre:'Literary fiction', color:'#59706a', description:'A small coastal town, a weather station, and the letters a daughter never meant to find. An original sample story for this reader prototype.', pages:['The Quiet Between Tides','Chapter One · The weather house\n\nThe sea had a way of making every promise sound temporary. From the window of the old weather house, Lena watched the morning pull its gray-blue coat over the harbor. The boats were still. The gulls were not.\n\nHer grandmother used to say that the tide kept a second calendar, one written where nobody could see it. Lena had never believed her until the day the house was left to her, with its crooked floorboards and a drawer full of envelopes addressed in a hand she knew by heart.','She found the first letter beneath the brass barometer, folded twice and softened at the edges. Outside, a buoy sounded once, then again. The note began without a greeting: If you are reading this, the tide has turned.\n\nLena sat at the kitchen table. Dust made a pale constellation in the slant of light. For the first time since she had arrived, the house felt less like an inheritance and more like a question.','At the end of the lane, the harbor keeper was raising the day’s first flag. The wind moved through the grass in long, quiet strokes. Lena placed the letter beside her cup and listened to the building settle around her.'] },
  { id:'fieldnotes', title:'Field Notes for the Moon', author:'Ivo Serrin', genre:'Nature & science', color:'#8b7054', description:'An amateur astronomer makes a nightly record of what changes, and what only appears to.', pages:['Field Notes for the Moon','Entry 01 · A borrowed telescope\n\nAt 9:14 the moon cleared the roofline. I had expected drama; instead there was a patient brightness, a coin held just beyond reach. The telescope was borrowed from the school on a promise to return it without fingerprints.','Entry 02 · The dark side of a Tuesday\n\nClouds came in from the west. I wrote down their shape anyway: a procession of unhurried ships. A notebook is useful for recording what cannot be kept.','Entry 03 · Waxing\n\nThe neighborhood went quiet by eleven. In the eyepiece, the craters held their shadows like small bowls. I wondered how often a person has to look before looking becomes a kind of knowing.'] },
  { id:'bluehour', title:'A Map of the Blue Hour', author:'Nell Aoki', genre:'Essays', color:'#526b80', description:'Brief, tender essays on cities at their softest hour and the people who keep them moving.', pages:['A Map of the Blue Hour','I · Before the first train\n\nAt five in the morning, the city belongs to people whose names the day will never learn. The baker unlocks a side door. A street sweeper makes one long pass beneath the plane trees. In the station, a woman in a yellow scarf reads the same page twice.','II · The river path\n\nThere is a particular blue that arrives before sunrise, when windows look like water and the river seems to be carrying the entire sky downstream. I walk until the first cafes turn on their lights.','III · Last light\n\nBy evening the day has gathered its loose ends. A cyclist coasts through the square; a child counts the pigeons. Every street looks briefly like a place one might begin again.'] },
  { id:'smallhours', title:'The Small Hours Club', author:'Theo North', genre:'Mystery', color:'#795c64', description:'A night librarian and a missing manuscript make a curious case of the after-hours.', pages:['The Small Hours Club','Chapter One · After closing\n\nThe library had its own night noises: the click of the radiator, the settling stacks, and, at exactly midnight, the soft chime of the old elevator. Mae had worked here seven years and still turned toward it every time.','A book was missing from the locked cabinet. Not valuable, not famous. Just a slim green volume with no title on its spine and a return slip dated tomorrow.','Mae took out her notebook. The building was quiet enough to hear a mystery beginning.'] },
  { id:'orchard', title:'An Orchard in Winter', author:'Ruth Bell', genre:'Literary fiction', color:'#777458', description:'A family gathers after a long absence among the dormant trees of their childhood.', pages:['An Orchard in Winter','The orchard looked smaller beneath snow. Rowan remembered it as a kingdom, every tree a room with a door made of branches. Now the rows stood open to the sky, and the old shed leaned toward the hill.','Her brother was already there, brushing frost from the bench with his glove. Neither of them mentioned the years between their last visit and this one. The trees did not ask.'] },
  { id:'goodweather', title:'A Brief History of Good Weather', author:'S. R. Calder', genre:'Essays', color:'#9a7855', description:'Small observations about weather, memory, and the rituals that make a place feel like home.', pages:['A Brief History of Good Weather','The forecast promised sun after lunch. I made no plans, which is how I knew I was beginning to trust it. On the stoop, the neighbor had left a jar of lemon verbena for anyone who wanted it.','Rain has a way of making ordinary rooms seem borrowed. Good weather, on the other hand, lends the world back to us slowly.'] },
  { id:'island', title:'The Island of Ordinary Things', author:'Juniper Vale', genre:'Fantasy', color:'#68715d', description:'A gentle fable about an island where lost objects find their way home.', pages:['The Island of Ordinary Things','The island appeared only when someone misplaced something they truly needed. A red mitten. A word for forgiveness. The brass key to a door that had been painted over.','Mira arrived on a Tuesday with no shoes and a pocket full of buttons. On the shore, the lighthouse keeper was sorting a box of mismatched spoons.'] },
  { id:'slow', title:'How to Make a Slow Morning', author:'Ada Finch', genre:'Wellbeing', color:'#927b6f', description:'A field guide to gentler starts, written for people who are learning to leave room.', pages:['How to Make a Slow Morning','Begin by opening a window. Not because the room needs air, although it probably does, but because a little weather changes the scale of everything.','Put water on to boil. While you wait, stand still long enough to notice the light moving across the counter. It is not a task. That is the point.'] },
];
const seedPrefs: Prefs = { displayName:'Reader', theme:'light', font:'Literata', size:20, spacing:1.8 };
function readStorage<T>(key:string, fallback:T):T { try { const value=localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function Cover({book, onClick}:{book:Book;onClick?:()=>void}) {
  return <div className="cover" onClick={onClick} style={{background:`linear-gradient(145deg, ${book.color}, ${book.color}cc 70%, #394742)`}} role={onClick?'button':undefined} tabIndex={onClick?0:undefined} onKeyDown={onClick?(e)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onClick();}}:undefined} data-testid={`cover-${book.id}`}><div className="cover-title">{book.title}</div><div className="cover-author">{book.author}</div></div>;
}
function App() {
  const [location, setLocation] = useLocation();
  const [prefs,setPrefs] = useState<Prefs>(()=>readStorage('kindle-demo-prefs',seedPrefs));
  const [wishlist,setWishlist] = useState<string[]>(()=>readStorage('kindle-demo-wishlist',['fieldnotes']));
  const [shelf,setShelf] = useState<string[]>(()=>readStorage('kindle-demo-library',['tideline','bluehour','smallhours','orchard']));
  const [progress,setProgress] = useState<Record<string,number>>(()=>readStorage('kindle-demo-progress',{tideline:1,bluehour:0,smallhours:1}));
  const [pdfs,setPdfs] = useState<LocalPdf[]>([]);
  const [toast,setToast] = useState('');
  useEffect(()=>{localStorage.setItem('kindle-demo-prefs',JSON.stringify(prefs));document.documentElement.classList.toggle('dark',prefs.theme==='dark');document.documentElement.dataset.theme=prefs.theme;},[prefs]);
  useEffect(()=>{localStorage.setItem('kindle-demo-wishlist',JSON.stringify(wishlist));},[wishlist]);
  useEffect(()=>{localStorage.setItem('kindle-demo-library',JSON.stringify(shelf));},[shelf]);
  useEffect(()=>{localStorage.setItem('kindle-demo-progress',JSON.stringify(progress));},[progress]);
  useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(''),2600);return()=>window.clearTimeout(timer);},[toast]);
  const toggleWish=(id:string)=>setWishlist(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const startBook=(id:string)=>{if(!shelf.includes(id))setShelf(current=>[id,...current]);setLocation(`/reader/${id}`);};
  const shared={prefs,setPrefs,wishlist,toggleWish,shelf,setShelf,progress,setProgress,pdfs,setPdfs,toast,setToast,startBook};
  return <div className="shell">
    {location.startsWith('/reader/') ? <Switch><Route path="/reader/:bookId"><Reader {...shared}/></Route></Switch> : <><Header theme={prefs.theme} toggleTheme={()=>setPrefs(p=>({...p,theme:p.theme==='dark'?'light':'dark'}))}/><Switch>
      <Route path="/"><LibraryPage {...shared}/></Route>
      <Route path="/library"><LibraryPage {...shared}/></Route>
      <Route path="/store"><StorePage {...shared}/></Route>
      <Route path="/wishlist"><WishlistPage {...shared}/></Route>
      <Route path="/settings"><SettingsPage {...shared}/></Route>
      <Route path="/login"><AuthPage mode="login" setToast={setToast}/></Route>
      <Route path="/signup"><AuthPage mode="signup" setToast={setToast}/></Route>
      <Route><NotFound/></Route>
    </Switch></>}
    {toast&&<div role="status" className="toast">{toast}</div>}
  </div>;
}
type Shared = {prefs:Prefs;setPrefs:Dispatch<SetStateAction<Prefs>>;wishlist:string[];toggleWish:(id:string)=>void;shelf:string[];setShelf:Dispatch<SetStateAction<string[]>>;progress:Record<string,number>;setProgress:Dispatch<SetStateAction<Record<string,number>>>;pdfs:LocalPdf[];setPdfs:Dispatch<SetStateAction<LocalPdf[]>>;toast:string;setToast:(s:string)=>void;startBook:(id:string)=>void};
function Header({theme,toggleTheme}:{theme:Prefs['theme'];toggleTheme:()=>void}) {
  const [location] = useLocation();
  const nav=[['/library','Library',LibraryBig],['/store','Discover',Search],['/wishlist','Saved',Heart],['/settings','Settings',SettingsIcon]] as const;
  return <header className="topbar"><Link href="/library" className="brand"><span className="brand-mark"><BookOpen size={16}/></span><span>kindle <span style={{fontSize:13,fontStyle:'italic'}}>reader</span></span></Link><nav className="nav" aria-label="Main navigation">{nav.map(([href,label,Icon])=><Link href={href} key={href} className={location===href?'active':''} data-testid={`link-${label.toLowerCase()}`}><Icon size={15}/><span>{label}</span></Link>)}</nav><div className="nav-actions"><Link href="/login" className="btn small hide-mobile">Demo account</Link><button className="icon-btn" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} onClick={toggleTheme} data-testid="button-theme">{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button></div></header>;
}
function BookGrid({items, wishlist, toggleWish, startBook, showWish=true, onDetails}:{items:Book[];wishlist:string[];toggleWish:(id:string)=>void;startBook:(id:string)=>void;showWish?:boolean;onDetails?:(book:Book)=>void}) {
  if(!items.length)return <div className="panel" style={{padding:36,textAlign:'center'}}><BookOpen size={24} style={{margin:'0 auto 10px',color:'hsl(var(--muted-foreground))'}}/><p className="serif" style={{fontSize:21,margin:'0 0 6px'}}>A little room for a new story.</p><p className="muted" style={{fontSize:13,margin:'0 0 18px'}}>Nothing here just yet. Find something that feels right.</p><Link className="btn primary small" href="/store">Browse the store</Link></div>;
  return <div className="grid-books">{items.map(book=><article className="book-card fade-in" key={book.id} data-testid={`card-book-${book.id}`}><div style={{position:'relative'}}><Cover book={book} onClick={()=>startBook(book.id)}/>{showWish&&<button className="icon-btn" style={{position:'absolute',right:7,top:7,background:'hsl(var(--card)/.92)'}} aria-label={wishlist.includes(book.id)?`Remove ${book.title} from wishlist`:`Save ${book.title} to wishlist`} onClick={()=>toggleWish(book.id)} data-testid={`button-wishlist-${book.id}`}><Heart size={17} fill={wishlist.includes(book.id)?'currentColor':'none'} color={wishlist.includes(book.id)?'#9c625b':undefined}/></button>}</div><div className="book-meta"><h3>{onDetails?<button onClick={()=>onDetails(book)} style={{padding:0,border:0,background:'none',color:'inherit',cursor:'pointer',textAlign:'left',font:'inherit'}}>{book.title}</button>:book.title}</h3><p>{book.author}</p><p style={{marginTop:5,fontSize:10,letterSpacing:'.04em'}}>{book.genre} · DEMO STORY</p></div></article>)}</div>;
}
function LibraryPage(p:Shared) {
  const [filter,setFilter]=useState('All books');
  const [pdfUrl,setPdfUrl]=useState('');
  const [pdfName,setPdfName]=useState('');
  const inputId='local-pdf-input';
  const libraryBooks=books.filter(book=>p.shelf.includes(book.id));
  const currently=libraryBooks.find(b=>(p.progress[b.id]??0)>0)??libraryBooks[0];
  const filtered=filter==='All books'?libraryBooks:filter==='In progress'?libraryBooks.filter(b=>(p.progress[b.id]??0)>0):libraryBooks.filter(b=>(p.progress[b.id]??0)===0);
  function importPdf(file?:File) { if(!file)return;if(file.type!=='application/pdf'){p.setToast('Choose a PDF file to import.');return;}const url=URL.createObjectURL(file);const id=`pdf-${Date.now()}`;setPdfUrl(url);setPdfName(file.name);p.setPdfs(current=>[{id,title:file.name.replace(/\.pdf$/i,''),url},...current]);p.setToast('PDF opened locally in this browser.'); }
  return <main className="main fade-in"><div className="split-head"><div><div className="eyebrow">Your reading room</div><h1 className="page-title">Good to see you, {p.prefs.displayName || 'Reader'}.</h1><p className="lead">A quiet place for the stories you’re carrying with you.</p></div><label className="btn" htmlFor={inputId}><Upload size={15}/> Import a PDF<input id={inputId} type="file" accept="application/pdf,.pdf" hidden onChange={e=>{importPdf(e.target.files?.[0]);e.currentTarget.value='';}} data-testid="input-pdf"/></label></div>
    {currently&&<section className="panel hero-reading" aria-label="Continue reading"><Cover book={currently} onClick={()=>p.startBook(currently.id)}/><div><div className="eyebrow">Pick up where you left off</div><h2 className="serif" style={{fontSize:28,fontWeight:500,margin:'8px 0 5px'}}>{currently.title}</h2><p className="muted" style={{fontSize:13,margin:'0 0 16px'}}>by {currently.author} · {Math.max(1,Math.round(((p.progress[currently.id]??0)+1)/currently.pages.length*100))}% read</p><div className="progress-track" style={{maxWidth:360,marginBottom:18}}><div className="progress-fill" style={{width:`${Math.max(9,((p.progress[currently.id]??0)+1)/currently.pages.length*100)}%`}}/></div><button className="btn primary small" onClick={()=>p.startBook(currently.id)} data-testid="button-continue"><BookOpen size={14}/> Continue reading</button></div></section>}
    <div className="section-head"><h2>Your library</h2><span className="muted" style={{fontSize:12}}>{libraryBooks.length} {libraryBooks.length===1?'book':'books'}</span></div>
    <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:23}}>{['All books','In progress','Not started'].map(x=><button className={`tag ${filter===x?'active':''}`} onClick={()=>setFilter(x)} key={x} data-testid={`filter-${x.toLowerCase().replace(' ','-')}`}>{x}</button>)}</div>
    <BookGrid items={filtered} wishlist={p.wishlist} toggleWish={p.toggleWish} startBook={p.startBook} showWish={false}/>
    <div className="section-head" style={{marginTop:44}}><h2>Imported on this device</h2><span className="muted" style={{fontSize:12}}>Never uploaded</span></div>
    {p.pdfs.length===0?<div className="panel" style={{padding:22,display:'flex',alignItems:'center',gap:14}}><div style={{width:42,height:42,borderRadius:14,background:'hsl(var(--secondary))',display:'grid',placeItems:'center'}}><Upload size={17}/></div><div><b style={{fontSize:13}}>Bring your own reading</b><p className="muted" style={{fontSize:12,margin:'4px 0 0'}}>Choose a PDF from this device. The file stays in your browser and is never sent anywhere.</p></div></div>:p.pdfs.map(pdf=><div className="panel" key={pdf.id} style={{padding:15,display:'flex',alignItems:'center',gap:13,marginBottom:8}}><BookOpen size={20}/><div style={{flex:1}}><b style={{fontSize:13}}>{pdf.title}</b><div className="muted" style={{fontSize:11,marginTop:3}}>Local PDF · available in this browser session</div></div><button className="btn small" onClick={()=>{setPdfUrl(pdf.url);setPdfName(pdf.title);}} data-testid="button-open-pdf">Open PDF</button><button className="icon-btn" aria-label={`Remove ${pdf.title}`} onClick={()=>{URL.revokeObjectURL(pdf.url);p.setPdfs(list=>list.filter(item=>item.id!==pdf.id));}}><X size={16}/></button></div>)}
    {pdfUrl&&<div role="dialog" aria-modal="true" aria-label={pdfName} style={{position:'fixed',inset:0,zIndex:60,background:'#171612e8',display:'grid',placeItems:'center',padding:16}}><div style={{width:'min(900px,100%)',height:'min(90dvh,900px)',background:'hsl(var(--card))',borderRadius:16,display:'flex',flexDirection:'column',overflow:'hidden'}}><div style={{padding:'12px 16px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:13}}>{pdfName} <span className="muted">· local file</span></span><button className="icon-btn" onClick={()=>setPdfUrl('')} aria-label="Close PDF"><X size={18}/></button></div><iframe src={pdfUrl} title={pdfName} style={{border:0,flex:1,background:'#fff'}}/></div></div>}
    <p className="notice">Prototype library · Sample titles and reading text are original demo content. This is not a real bookstore or account service.</p>
  </main>;
}
function StorePage(p:Shared) {
  const [query,setQuery]=useState('');const [genre,setGenre]=useState('Everything');const [detail,setDetail]=useState<Book|null>(null);
  const genres=['Everything',...Array.from(new Set(books.map(b=>b.genre)))];
  const results=useMemo(()=>books.filter(book=>(genre==='Everything'||book.genre===genre)&&`${book.title} ${book.author} ${book.genre}`.toLowerCase().includes(query.toLowerCase())),[query,genre]);
  return <main className="main fade-in"><div className="split-head"><div><div className="eyebrow">The sample shelf</div><h1 className="page-title">Find your next somewhere.</h1><p className="lead">A small catalogue of invented books, here to explore the prototype. No purchases or downloads happen here.</p></div><div className="searchbox"><Search size={16} className="muted"/><input type="search" placeholder="Search books or authors" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search sample books" data-testid="input-search-books"/></div></div>
    <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:30}}>{genres.map(item=><button key={item} className={`tag ${genre===item?'active':''}`} onClick={()=>setGenre(item)} data-testid={`genre-${item.toLowerCase().replaceAll(' ','-').replace('&','and')}`}>{item}</button>)}</div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18}}><h2 className="serif" style={{fontSize:24,fontWeight:500,margin:0}}>{genre==='Everything'?'A few good beginnings':genre}</h2><span className="muted" style={{fontSize:12}}>{results.length} titles</span></div>
    <BookGrid items={results} wishlist={p.wishlist} toggleWish={p.toggleWish} startBook={p.startBook} onDetails={setDetail}/>
    <p className="notice">All catalogue items are fictional prototype records. “Read sample” opens original demo text. Saving a title only changes this browser’s local wishlist; no books are sold, purchased, or delivered.</p>
    {detail&&<div role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={()=>setDetail(null)} style={{position:'fixed',inset:0,zIndex:50,background:'#17161299',display:'grid',placeItems:'center',padding:18}}><div className="panel" onClick={e=>e.stopPropagation()} style={{width:'min(680px,100%)',padding:25,display:'grid',gridTemplateColumns:'minmax(110px,165px) 1fr',gap:25,position:'relative'}}><button className="icon-btn" onClick={()=>setDetail(null)} aria-label="Close book details" style={{position:'absolute',right:12,top:12}}><X size={17}/></button><Cover book={detail}/><div style={{paddingTop:15}}><div className="eyebrow">{detail.genre} · DEMO TITLE</div><h2 id="detail-title" className="serif" style={{fontSize:29,fontWeight:500,lineHeight:1.12}}>{detail.title}</h2><p className="muted" style={{fontSize:13}}>by {detail.author}</p><p style={{fontSize:13,lineHeight:1.7}}>{detail.description}</p><p className="muted" style={{fontSize:11}}>Original sample text · {detail.pages.length} reading sections</p><div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:20}}><button className="btn primary" onClick={()=>{setDetail(null);p.startBook(detail.id);}}>Read sample</button><button className="btn" onClick={()=>p.toggleWish(detail.id)}><Heart size={15} fill={p.wishlist.includes(detail.id)?'currentColor':'none'}/>{p.wishlist.includes(detail.id)?'Saved':'Save to wishlist'}</button></div></div></div></div>}
  </main>;
}
function WishlistPage(p:Shared) {
  const items=books.filter(b=>p.wishlist.includes(b.id));
  return <main className="main fade-in"><div className="eyebrow">Kept for later</div><h1 className="page-title">Your wishlist.</h1><p className="lead" style={{marginBottom:32}}>A little shelf for stories you might want to return to. Saved only in this browser.</p><BookGrid items={items} wishlist={p.wishlist} toggleWish={p.toggleWish} startBook={p.startBook}/><p className="notice">Wishlist changes are stored locally on this device. This prototype does not offer real purchases or book delivery.</p></main>;
}
function SettingsPage(p:Shared) {
  const update=<K extends keyof Prefs>(key:K,value:Prefs[K])=>p.setPrefs(current=>({...current,[key]:value}));
  return <main className="main fade-in"><div className="eyebrow">Make it yours</div><h1 className="page-title">Reading preferences.</h1><p className="lead" style={{marginBottom:30}}>A few small adjustments can make a page feel like your own.</p><div className="panel" style={{padding:'5px 26px'}}>
    <div className="setting-row"><div><h3>Display name</h3><p>Used to greet you in your personal library.</p></div><input className="input" value={p.prefs.displayName} onChange={e=>update('displayName',e.target.value)} aria-label="Display name" data-testid="input-display-name"/></div>
    <div className="setting-row"><div><h3>Page tone</h3><p>Choose the light that feels right for reading.</p></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{(['light','paper','dark'] as const).map(t=><button key={t} onClick={()=>update('theme',t)} className={`tag ${p.prefs.theme===t?'active':''}`} data-testid={`theme-${t}`}>{t==='light'?'Daylight':t==='paper'?'Paper':'Night'}</button>)}</div></div>
     <div className="setting-row"><div><h3>Typeface</h3><p>Choose a familiar voice for the page.</p></div><select className="input" value={p.prefs.font} onChange={e=>update('font',e.target.value as Prefs['font'])} aria-label="Reader typeface" data-testid="select-font"><option value="Literata">Literata · book serif</option><option value="Georgia">Georgia · classic serif</option><option value="DM Sans">DM Sans · clean sans</option></select></div>
    <div className="setting-row"><div><h3>Font size <span className="muted">{p.prefs.size}px</span></h3><p>Make the page comfortable at a glance.</p></div><input type="range" min="16" max="30" step="1" value={p.prefs.size} onChange={e=>update('size',Number(e.target.value))} aria-label="Font size" data-testid="range-font-size"/></div>
    <div className="setting-row"><div><h3>Line spacing <span className="muted">{p.prefs.spacing.toFixed(1)}</span></h3><p>Give each line a little more or less room.</p></div><input type="range" min="1.4" max="2.2" step="0.1" value={p.prefs.spacing} onChange={e=>update('spacing',Number(e.target.value))} aria-label="Line spacing" data-testid="range-line-spacing"/></div>
  </div><div style={{display:'flex',alignItems:'center',gap:9,marginTop:18,fontSize:12,color:'hsl(var(--muted-foreground))'}}><Check size={15}/> Preferences save automatically on this device.</div><p className="notice">Prototype settings only. No profile or reading data is sent to a service.</p></main>;
}
function AuthPage({mode,setToast}:{mode:'login'|'signup';setToast:(s:string)=>void}) {
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [done,setDone]=useState(false);
  const signup=mode==='signup';
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setDone(true);setToast('Demo only — no account was created or information saved.');setName('');setEmail('');setPassword('');}
  return <main className="auth-wrap fade-in"><section className="panel auth-card"><div className="eyebrow">{signup?'A personal reading space':'Welcome back'}</div><h1 className="serif" style={{fontSize:37,fontWeight:500,letterSpacing:-1,margin:'9px 0'}}> {signup?'Make room for stories.':'Come on in.'}</h1><p className="muted" style={{fontSize:13,lineHeight:1.65,marginBottom:25}}>This is a visual demo. You can try the form, but details are never stored or sent and no account is created.</p>{done&&<div role="status" style={{background:'hsl(var(--accent)/.6)',padding:12,borderRadius:11,fontSize:12,marginBottom:18}}>Thanks for trying the demo. Nothing was saved.</div>}<form onSubmit={submit} style={{display:'grid',gap:14}}>{signup&&<label style={{fontSize:12,fontWeight:600}}>Your name<input className="input" style={{marginTop:6}} value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?" autoComplete="off" required/></label>}<label style={{fontSize:12,fontWeight:600}}>Email address<input className="input" style={{marginTop:6}} type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="off" required/></label><label style={{fontSize:12,fontWeight:600}}>Password<input className="input" style={{marginTop:6}} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter anything for the demo" autoComplete="new-password" required/></label><button className="btn primary" type="submit" style={{marginTop:7}}>{signup?'Create demo profile':'Continue to demo'}</button></form><div style={{textAlign:'center',fontSize:12,marginTop:22}}>{signup?'Already have a demo? ':'New to the reading room? '}<Link href={signup?'/login':'/signup'} style={{color:'hsl(var(--primary))',fontWeight:700}}>{signup?'Sign in':'Create a demo profile'}</Link></div><div className="notice" style={{marginTop:24}}>No authentication, account storage, or network requests are used by this prototype.</div></section></main>;
}
function Reader(p:Shared) {
  const params=useParams<{bookId:string}>();const book=books.find(b=>b.id===params.bookId);const localPdf=p.pdfs.find(item=>item.id===params.bookId);
  const [page,setPage]=useState(()=>p.progress[params.bookId]??0);const [contents,setContents]=useState(false);const [note,setNote]=useState('');const [savedNotes,setSavedNotes]=useState<string[]>(()=>readStorage(`kindle-notes-${params.bookId}`,[]));const [highlights,setHighlights]=useState<string[]>(()=>readStorage(`kindle-highlights-${params.bookId}`,[]));const [showNote,setShowNote]=useState(false);
  useEffect(()=>{setPage(p.progress[params.bookId]??0);},[params.bookId]);
  useEffect(()=>{p.setProgress(current=>({...current,[params.bookId]:page}));},[page,params.bookId]);
  useEffect(()=>{localStorage.setItem(`kindle-notes-${params.bookId}`,JSON.stringify(savedNotes));},[savedNotes,params.bookId]);
  useEffect(()=>{localStorage.setItem(`kindle-highlights-${params.bookId}`,JSON.stringify(highlights));},[highlights,params.bookId]);
  useEffect(()=>{function keys(e:KeyboardEvent){if(e.key==='ArrowRight')setPage(v=>Math.min((book?.pages.length??1)-1,v+1));if(e.key==='ArrowLeft')setPage(v=>Math.max(0,v-1));if(e.key==='Escape')setContents(false);}window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[book]);
  if(localPdf)return <div className="reader"><div className="reader-top"><Link href="/library" className="btn small"><ChevronLeft size={15}/> Library</Link><span style={{fontSize:13}}>{localPdf.title} <span className="muted">· local PDF</span></span><button className="icon-btn" onClick={()=>p.setToast('PDF stays in this browser session.')} aria-label="Local file information"><BookOpen size={17}/></button></div><iframe title={localPdf.title} src={localPdf.url} style={{border:0,flex:1,minHeight:'calc(100dvh - 70px)',background:'#fff'}}/></div>;
  if(!book)return <main className="main"><div className="panel" style={{padding:30}}><h1 className="serif">This story isn’t on your shelf.</h1><Link className="btn primary" href="/store">Find a sample story</Link></div></main>;
  const total=book.pages.length;const pct=Math.round(((page+1)/total)*100);
  const saveNote=()=>{if(!note.trim())return;setSavedNotes(current=>[...current,`Page ${page+1}: ${note.trim()}`]);setNote('');setShowNote(false);p.setToast('Note saved on this device.');};
  const highlightSelection=()=>{const selected=window.getSelection()?.toString().trim();if(!selected){p.setToast('Select a passage on the page first.');return;}setHighlights(current=>[...current,selected]);window.getSelection()?.removeAllRanges();p.setToast('Passage highlighted on this device.');};
  return <div className="reader" style={{'--reader-font':p.prefs.font==='DM Sans'?'DM Sans':p.prefs.font,'--reader-size':`${p.prefs.size}px`,'--reader-leading':p.prefs.spacing} as CSSProperties}>
    <div className="reader-top"><Link href="/library" className="btn small"><ChevronLeft size={15}/><span className="hide-mobile">Library</span></Link><div style={{textAlign:'center',minWidth:0}}><div className="serif" style={{fontSize:16,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{book.title}</div><div className="muted" style={{fontSize:10,marginTop:2}}>{book.author} · DEMO TEXT</div></div><button className={`icon-btn`} aria-label={p.wishlist.includes(book.id)?'Remove bookmark':'Bookmark this story'} onClick={()=>p.toggleWish(book.id)} data-testid="button-reader-bookmark"><Bookmark size={17} fill={p.wishlist.includes(book.id)?'currentColor':'none'}/></button></div>
    <div className="reader-body"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:35}}><span className="eyebrow">{page===0?'Title page':`Section ${page} of ${total-1}`}</span><div className="reader-tool"><button className="icon-btn" aria-label="Font smaller" onClick={()=>p.setPrefs(c=>({...c,size:Math.max(16,c.size-1)}))}>A−</button><button className="icon-btn" aria-label="Font larger" onClick={()=>p.setPrefs(c=>({...c,size:Math.min(30,c.size+1)}))}>A+</button><button className="icon-btn" aria-label="Open contents" onClick={()=>setContents(!contents)}><List size={17}/></button></div></div>
      <article className="reader-page" data-testid="reader-content">{page===0?<><h1>{book.pages[0]}</h1><p style={{fontSize:'.72em',letterSpacing:'.12em',textTransform:'uppercase'}}>{book.author}</p><p style={{marginTop:58,fontSize:'.72em',color:'hsl(var(--muted-foreground))'}}>A sample story from the Kindle Reader demo library</p></>:<><h1>{book.pages[page]?.split('\n')[0]}</h1><p>{book.pages[page]?.split('\n\n').slice(1).join('\n\n')}</p></>}</article>
      {(savedNotes.length>0||highlights.length>0)&&<div style={{borderTop:'1px solid hsl(var(--border))',marginTop:50,paddingTop:16}}><div className="eyebrow" style={{marginBottom:10}}>Highlights & notes</div>{highlights.map((text,i)=><div key={`h-${i}`} style={{fontSize:12,padding:'9px 0',color:'hsl(var(--muted-foreground))'}}><span className="highlight">{text}</span><button className="icon-btn" style={{display:'inline-grid',verticalAlign:'middle',width:27,height:27}} aria-label="Delete highlight" onClick={()=>setHighlights(current=>current.filter((_,idx)=>idx!==i))}><X size={13}/></button></div>)}{savedNotes.map((text,i)=><div key={`n-${i}`} style={{fontSize:12,padding:'9px 0',color:'hsl(var(--muted-foreground))'}}>{text}<button className="icon-btn" style={{display:'inline-grid',verticalAlign:'middle',width:27,height:27}} aria-label="Delete note" onClick={()=>setSavedNotes(current=>current.filter((_,idx)=>idx!==i))}><X size={13}/></button></div>)}</div>}
      {showNote&&<div style={{marginTop:28}}><label htmlFor="reader-note" className="eyebrow">A note for this page</label><textarea id="reader-note" className="input" value={note} onChange={e=>setNote(e.target.value)} placeholder="What would you like to remember?" rows={3} style={{display:'block',marginTop:8}}/><div style={{display:'flex',gap:8,marginTop:9}}><button className="btn primary small" onClick={saveNote}>Save note</button><button className="btn small" onClick={()=>setShowNote(false)}>Cancel</button></div></div>}
    </div>
    <div className="reader-bottom"><div style={{display:'flex',alignItems:'center',gap:10,minWidth:0}}><span style={{fontSize:11,whiteSpace:'nowrap'}}>{pct}%</span><div className="progress-track" style={{width:'min(170px,25vw)'}}><div className="progress-fill" style={{width:`${pct}%`}}/></div></div><span className="muted hide-mobile" style={{fontSize:11}}>Page {page+1} of {total}</span><div className="reader-tool"><button className="btn small" disabled={page===0} onClick={()=>setPage(v=>Math.max(0,v-1))} aria-label="Previous page" data-testid="button-previous-page"><ChevronLeft size={15}/><span className="hide-mobile">Previous</span></button><button className="btn small" onClick={highlightSelection} data-testid="button-highlight"><span className="highlight" style={{fontSize:14}}>a</span><span className="hide-mobile">Highlight</span></button><button className="btn small" onClick={()=>setShowNote(v=>!v)} data-testid="button-add-note">Note</button><button className="btn small primary" disabled={page>=total-1} onClick={()=>setPage(v=>Math.min(total-1,v+1))} aria-label="Next page" data-testid="button-next-page"><span className="hide-mobile">Next</span><ChevronRight size={15}/></button></div></div>
    {contents&&<div role="dialog" aria-modal="true" aria-label="Story contents" style={{position:'fixed',inset:0,zIndex:55,background:'#17161270',display:'flex',justifyContent:'flex-end'}} onClick={()=>setContents(false)}><aside onClick={e=>e.stopPropagation()} style={{width:'min(360px,90vw)',height:'100%',background:'hsl(var(--background))',padding:24,boxShadow:'-12px 0 35px #0002'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 className="serif" style={{fontWeight:500}}>Contents</h2><button className="icon-btn" onClick={()=>setContents(false)} aria-label="Close contents"><X size={17}/></button></div><p className="muted" style={{fontSize:12}}>Choose a section to jump to.</p>{book.pages.map((line,i)=><button key={i} onClick={()=>{setPage(i);setContents(false);}} style={{display:'block',textAlign:'left',width:'100%',border:0,borderBottom:'1px solid hsl(var(--border))',background:'transparent',padding:'16px 2px',color:'inherit',cursor:'pointer',fontFamily:'var(--app-font-serif)'}}>{i===0?'Title page':line.split('\n')[0]}{i===page&&<span style={{float:'right',color:'hsl(var(--primary))',font:'11px var(--app-font-sans)'}}>Reading</span>}</button>)}</aside></div>}
  </div>;
}
function NotFound(){return <main className="main"><div className="panel" style={{padding:35}}><div className="eyebrow">Nothing on this page</div><h1 className="page-title">Let’s find our way back.</h1><Link href="/library" className="btn primary">Return to your library</Link></div></main>}
export default App;
